from .PreguntaOpcionMultipleDto import PreguntaOpcionMultipleDto
from .PreguntaEnsayoDto import PreguntaEnsayoDto
from .PreguntaEmparejamientoDto import PreguntaEmparejamientoDto
from .PreguntaVerdaderoFalsoDto import PreguntaVerdaderoFalsoDto